In [69]:
import polars as pl

In [70]:
df = pl.read_parquet("../data/clean/train.parquet")

In [71]:
df.filter((pl.col("date_utc")==pl.lit("2017-11-19")) & (pl.col("track")==pl.lit("mudgee")) & (pl.col("racenum")==pl.lit("7"))).select("idx","win_bsp","placenum")

shape: (0, 3)
┌─────┬─────────┬──────────┐
│ idx ┆ win_bsp ┆ placenum │
│ --- ┆ ---     ┆ ---      │
│ str ┆ f32     ┆ i32      │
╞═════╪═════════╪══════════╡
└─────┴─────────┴──────────┘

In [72]:
idxs=[('2019-07-07 10:39:00.000000+00:00gawler120',), ('2019-07-07 10:45:00.000000+00:00albionpark110',), ('2019-07-07 10:48:00.000000+00:00darwin30',), ('2019-07-07 11:06:00.000000+00:00darwin40',), ('2019-07-07 11:22:00.000000+00:00darwin50',), ('2019-07-07 11:37:00.000000+00:00darwin60',), ('2019-07-07 11:52:00.000000+00:00darwin70',), ('2019-07-08 02:04:00.000000+00:00cranbourne10',), ('2019-07-08 02:07:00.000000+00:00bundaberg10',), ('2019-07-08 02:20:00.000000+00:00cranbourne20',), ('2019-07-08 02:28:00.000000+00:00bundaberg20',), ('2019-07-08 02:40:00.000000+00:00cranbourne30',), ('2019-07-08 02:45:00.000000+00:00bundaberg30',), ('2019-07-08 02:57:00.000000+00:00cranbourne40',), ('2019-07-08 03:07:00.000000+00:00bundaberg40',), ('2019-07-08 03:14:00.000000+00:00cranbourne50',), ('2019-07-08 03:22:00.000000+00:00bundaberg50',), ('2019-07-08 03:34:00.000000+00:00cranbourne60',), ('2019-07-08 03:42:00.000000+00:00bundaberg60',), ('2019-07-08 03:49:00.000000+00:00cranbourne70',), ('2019-07-08 03:57:00.000000+00:00bundaberg70',), ('2019-07-08 04:09:00.000000+00:00cranbourne80',), ('2019-07-08 04:17:00.000000+00:00bundaberg80',), ('2019-07-08 04:27:00.000000+00:00cranbourne90',), ('2019-07-08 04:37:00.000000+00:00bundaberg90',), ('2019-07-08 04:44:00.000000+00:00cranbourne100',), ('2019-07-08 04:48:00.000000+00:00ballarat10',), ('2019-07-08 04:52:00.000000+00:00bundaberg100',), ('2019-07-08 05:04:00.000000+00:00ballarat20',), ('2019-07-08 05:07:00.000000+00:00cranbourne110',), ('2019-07-08 05:19:00.000000+00:00ballarat30',), ('2019-07-08 05:32:00.000000+00:00northam10',)]
idx_set = set(idx[0] for idx in idxs)
df2=df.filter(pl.col("idx").is_in(idx_set)).select("idx","win_bsp","placenum")

In [73]:
(df2["win_bsp"]==0).sum()

0

In [74]:
bad_race = '2019-07-08 03:34:00.000000+00:00cranbourne60'
df.filter(pl.col("idx") == bad_race).select("idx","dogname","win_bsp","placenum")

shape: (8, 4)
┌─────────────────────────────────┬─────────────────┬──────────┬──────────┐
│ idx                             ┆ dogname         ┆ win_bsp  ┆ placenum │
│ ---                             ┆ ---             ┆ ---      ┆ ---      │
│ str                             ┆ str             ┆ f32      ┆ i32      │
╞═════════════════════════════════╪═════════════════╪══════════╪══════════╡
│ 2019-07-08 03:34:00.000000+00:… ┆ FLOJOMIKADO     ┆ 6.347511 ┆ 1        │
│ 2019-07-08 03:34:00.000000+00:… ┆ ENTWINED        ┆ 3.60631  ┆ 5        │
│ 2019-07-08 03:34:00.000000+00:… ┆ SMARTYPANTS     ┆ 3.8      ┆ 6        │
│ 2019-07-08 03:34:00.000000+00:… ┆ KIRANNABLUE     ┆ 4.973259 ┆ 8        │
│ 2019-07-08 03:34:00.000000+00:… ┆ SPECTATOR       ┆ 75.0     ┆ 7        │
│ 2019-07-08 03:34:00.000000+00:… ┆ SWEETGABRIELLA  ┆ 170.0    ┆ 4        │
│ 2019-07-08 03:34:00.000000+00:… ┆ DESTINIJAGUAR   ┆ 190.0    ┆ 2        │
│ 2019-07-08 03:34:00.000000+00:… ┆ FOURTHDIMENTION ┆ 17.0     ┆ 3        │
└─────────────────────────────────┴─────────────────┴──────────┴──────────┘

In [75]:
bad_race='2019-07-07 11:06:00.000000+00:00darwin40'
df.filter(pl.col("idx") == bad_race).select("idx","dogname","win_bsp","placenum")

shape: (0, 4)
┌─────┬─────────┬─────────┬──────────┐
│ idx ┆ dogname ┆ win_bsp ┆ placenum │
│ --- ┆ ---     ┆ ---     ┆ ---      │
│ str ┆ str     ┆ f32     ┆ i32      │
╞═════╪═════════╪═════════╪══════════╡
└─────┴─────────┴─────────┴──────────┘